theme: jekyll-theme-minimal
title: Benjamin D. Smith
<head>
  <link rel="shortcut icon" type="image/png" href="/img/favicon-32x32.png">
  <link rel="shortcut icon" sizes="32x32" href="/img/favicon-32x32.png">
  <link rel="apple-touch-icon" href="/img/favicon-32x32.png">
</head>
